services:
  playsock:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Primary Valkey env var; app also honors legacy PLAYSOCK_REDIS_ADDR for backward compatibility
      PLAYSOCK_VALKEY_ADDR: valkey:6379
      PLAYSOCK_ALLOWED_ORIGINS: "*"
      PLAYSOCK_QUEUE_TIMEOUT: 5m
    depends_on:
      - valkey
    restart: unless-stopped

  valkey:
    image: valkey/valkey:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: unless-stopped

volumes:
  valkey_data: