services:
  playsock:
    build: .
    ports:
      - "8080:8080"
    environment:
      PLAYSOCK_REDIS_ADDR: redis:6379
      PLAYSOCK_ALLOWED_ORIGINS: "*"
      PLAYSOCK_QUEUE_TIMEOUT: 5m
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data: