services:
  playsock:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PLAYSOCK_REDIS_ADDR=redis:6379
      - PLAYSOCK_ALLOWED_ORIGINS=*
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data: